# Generated by Django 3.1.4 on 2021-02-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0002_auto_20210216_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
    ]
